guessA = "1"
guessB = "2"
guessC = "3"
guessD = "4"
numHit = "4"
numBlow = "0"
# solnHash = "0x109243bde5fa6c2fe3f231697447a7e45853eade6727ca11faa5a935e434a703"
setpub = []

# guessA = "4"
# guessB = "5"
# guessC = "6"
# guessD = "7"
# numHit = "0"
# numBlow = "1"