guessA = "1"
guessB = "2"
guessC = "3"
guessD = "4"
numHit = "4"
numBlow = "0"
solnHash = "0x01deb83e303e2b30ea88be1741e769b3171a85cb77d709c8f503925c1328f264"
setpub = []

# guessA = "4"
# guessB = "5"
# guessC = "6"
# guessD = "7"
# numHit = "0"
# numBlow = "1"